FROM golang:1.26.2

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    make \
    git \
 && ln -s /usr/bin/python3 /usr/bin/python || true \
 && rm -rf /var/lib/apt/lists/*

# Cache de deps Go
COPY go.mod go.sum ./
RUN go mod download

# Python venv
COPY python/requirements-dev.txt /tmp/requirements-dev.txt
COPY python/requirements.txt /tmp/requirements.txt
RUN python3 -m venv /opt/venv \
 && /opt/venv/bin/pip install -r /tmp/requirements-dev.txt

ENV PATH="/opt/venv/bin:${PATH}"

# Instal·lar air
RUN go install github.com/air-verse/air@latest

CMD ["air", "-c", ".air.toml"]