services:
  watersystem-ml:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: watersystem-ml
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    environment:
        - INFLUXDB_URL=http://influxdb:8086
        - INFLUXDB_TOKEN=my-super-token
        - INFLUXDB_ORG=water-system
        - INFLUXDB_BUCKET=bonsai-data
        - MODEL_DIR=/tmp/models
        - SERVER_HOST=${SERVER_HOST:-:8080}
        - PYTHON_PATH=/opt/venv/bin/python
        - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-token_default}
        - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-12345}
        - ENV=LOCAL
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
        - OTEL_TRACES_SAMPLER=always_on
        - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    depends_on:
      - influxdb
      - lgtm
      - mockserver
    command: ["air", "-c", ".air.toml"]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE:-setup}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-change-me-please}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG:-water-system}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET:-bonsai-data}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-my-super-token}
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - influxdb2_config:/etc/influxdb2
    restart: unless-stopped

  lgtm:
      image: grafana/otel-lgtm:latest
      ports:
        - "3002:3000"
        - "4317:4317"
        - "4318:4318"
  mockserver:
      image: mockserver/mockserver:latest
      ports:
        - "1080:1080"
      volumes:
        - ./mockserver/expectations.json:/config/expectations.json
      environment:
        MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectations.json

volumes:
  influxdb2_data:
  influxdb2_config:
  go-mod-cache:
  go-build-cache: