apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-login
  namespace: watersystem-ml

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: ghcr-login
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ printf "%s:%s" .username .token | b64enc }}"
              }
            }
          }

  data:
    - secretKey: username
      remoteRef:
        key: secrets/k3s/ghcr
        property: username

    - secretKey: token
      remoteRef:
        key: secrets/k3s/ghcr
        property: token