---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - serviceaccount-default.yaml
  - pvc.yaml
  - externalsecret-influxdb.yaml
  - externalsecret-ntfy.yaml
  - externalsecret-postgres.yaml
  - externalsecret-watersystem.yaml
  - externalsecret-ghrc.yaml

commonLabels:
  app.kubernetes.io/part-of: watersystem-ml

