---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - secret-ghcr.yaml
  - serviceaccount-default.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/part-of: watersystem-ml

