apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watersystem-ml-models
  namespace: watersystem-ml
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi