apiVersion: ENC[AES256_GCM,data:1y4=,iv:tScnHDDHJPGnJ1P21Ga9+tJxd8vGfG0r5ynFlNProsA=,tag:u/pVxOoMY3/+c9FbqVwj6w==,type:str]
kind: ENC[AES256_GCM,data:yPpiYvmQ,iv:I/Crg05AfxrIRYrAzmBDAydmSs/DR1FhJwvWE5qFTbI=,tag:8FFfHDPBoGVoR0kZ4VKj8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xuxOhvtbLQmZpZwvBqVPiRIkMArF,iv:xkkFO3WF/koBEe5KxHW0gDg3D/VhTnkeDG2E9FmGRS0=,tag:oYA+trhUdeZhbZ9VuVhCeQ==,type:str]
    namespace: ENC[AES256_GCM,data:vDY1dcIw6g/7jK5w0/4=,iv:aAL9frdQNivIByAUOuVcpWlQS4I4Gbatbb8lCYutjD8=,tag:UyWRr1KeqXlWbaoCk2YS0A==,type:str]
type: ENC[AES256_GCM,data:mzOGmga2,iv:fnokBehP+8zQsb54uUwNQ5dZ9xtZDSsJbvhAKDRcPvc=,tag:NEkJ7bTSUdQ9pB5SV/URpA==,type:str]
stringData:
    INFLUXDB_BUCKET: ENC[AES256_GCM,data:m4UQeX6lZ3sCcTU=,iv:tOLbwdtDZPTd3ujgnmGym2d3VWxSKYSJjKkjJYOf+Ck=,tag:MGPmKMXL1vNxO+TcV0bQqA==,type:str]
    INFLUXDB_ORG: ENC[AES256_GCM,data:Km2qJg==,iv:8pWQ1bXteiY8itfCkl726Bu4UGoavdrngYrYabekzg4=,tag:+Y4zDmEuL9iSzS1yPPNvXQ==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:+XeFggVQEdkVmidcH6w7Ws42Syp3FiM9QSBF3SGCrTBMNU/9wxGDgcTxuw9yS7ADe9GhBvG+/Gy1oAdlcICcrA==,iv:ysIbkmA0BAFSma1nQfxpfY0T/IN/BBPmIiYJTJ4fj1k=,tag:JlGcm8ZyegtTgfMZS3tcVw==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:TzOBFQp0eyg=,iv:BZSVf7XxMuXZkDt3sL311JRkVCpx3Adn3YdweBbXtgE=,tag:NoJqJ57bJiz++upGLEKixg==,type:str]
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:0kogSDJRk6hISOLHSZKa7XA8StDpzl9NFcl1vJCxiRZXCBTVcFX7uGKwJds+cQ==,iv:FkMlcKo5OQSD1uKPyG+thiiIhMCNaeAiik3Zi5x05OI=,tag:1aObjkV814qxrkO9i/FtdA==,type:str]
sops:
    age:
        - recipient: age1jka78fpaprd5ywurm0cgxdznp8l4yhggw0yn4h6ejxf7a7q8d4ps9w4xqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR3ZTa0xkTVdTdk9QWGc3
            dEpIVTZrMVZQYkwzejFnVDFQY3hZMVpzTldBCnR5SDFRYUdXL292eStqSVZob1c4
            ZFpmcUpKUEt2WWRYVHBRNW5tQVM3alEKLS0tIDl1dVVOc2xBZnRDTVI5dktlM3A4
            d29ZSis0cERPdEpyMjZDQ1Z6amJORFUKtqR3z1eyTzGm63Xk9wbt8+S2prnQ1i+u
            KYsovppbqheuRUPSpltr1yF0d/XxgUHOzqhqTl7JK5SASlocCACQNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T16:11:08Z"
    mac: ENC[AES256_GCM,data:gC9XEacaQZ1x9aRyhjzC/u7OHCVZfrlK88er+XMFGUPIeXldzrl5XeC4F/I36TLV0+W2bnu74fc83xpCRMtujweX9LnskjASASVnQOj35kvd7cJ4teWEmB5+v2AIn3kc4W+9TOy6TfiProyci4bN9DtPP03dxJsLzuCrlatlNqQ=,iv:DuMqTEkY5L2ZVYuuub9tF3jbb+oM2UpdEP/DbElSSno=,tag:CpnuljrAD6ax+IbSPs7vDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
