// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ml

import (
	"context"
	"sync"
)

// Ensure, that PredictionRepositoryMock does implement PredictionRepository.
// If this is not the case, regenerate this file with moq.
var _ PredictionRepository = &PredictionRepositoryMock{}

// PredictionRepositoryMock is a mock implementation of PredictionRepository.
//
//	func TestSomethingThatUsesPredictionRepository(t *testing.T) {
//
//		// make and configure a mocked PredictionRepository
//		mockedPredictionRepository := &PredictionRepositoryMock{
//			GetFunc: func(ctx context.Context) ([]Prediction, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedPredictionRepository in code that requires PredictionRepository
//		// and then make assertions.
//
//	}
type PredictionRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context) ([]Prediction, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *PredictionRepositoryMock) Get(ctx context.Context) ([]Prediction, error) {
	if mock.GetFunc == nil {
		panic("PredictionRepositoryMock.GetFunc: method is nil but PredictionRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedPredictionRepository.GetCalls())
func (mock *PredictionRepositoryMock) GetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Ensure, that SoilMeasureRepositoryMock does implement SoilMeasureRepository.
// If this is not the case, regenerate this file with moq.
var _ SoilMeasureRepository = &SoilMeasureRepositoryMock{}

// SoilMeasureRepositoryMock is a mock implementation of SoilMeasureRepository.
//
//	func TestSomethingThatUsesSoilMeasureRepository(t *testing.T) {
//
//		// make and configure a mocked SoilMeasureRepository
//		mockedSoilMeasureRepository := &SoilMeasureRepositoryMock{
//			GetFunc: func(ctx context.Context) ([]SoilMeasure, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedSoilMeasureRepository in code that requires SoilMeasureRepository
//		// and then make assertions.
//
//	}
type SoilMeasureRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context) ([]SoilMeasure, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *SoilMeasureRepositoryMock) Get(ctx context.Context) ([]SoilMeasure, error) {
	if mock.GetFunc == nil {
		panic("SoilMeasureRepositoryMock.GetFunc: method is nil but SoilMeasureRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSoilMeasureRepository.GetCalls())
func (mock *SoilMeasureRepositoryMock) GetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
