// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ml

import (
	"context"
	"sync"
)

// Ensure, that PredictionRepositoryMock does implement PredictionRepository.
// If this is not the case, regenerate this file with moq.
var _ PredictionRepository = &PredictionRepositoryMock{}

// PredictionRepositoryMock is a mock implementation of PredictionRepository.
//
//	func TestSomethingThatUsesPredictionRepository(t *testing.T) {
//
//		// make and configure a mocked PredictionRepository
//		mockedPredictionRepository := &PredictionRepositoryMock{
//			GetFunc: func(ctx context.Context) ([]Prediction, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedPredictionRepository in code that requires PredictionRepository
//		// and then make assertions.
//
//	}
type PredictionRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context) ([]Prediction, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *PredictionRepositoryMock) Get(ctx context.Context) ([]Prediction, error) {
	if mock.GetFunc == nil {
		panic("PredictionRepositoryMock.GetFunc: method is nil but PredictionRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedPredictionRepository.GetCalls())
func (mock *PredictionRepositoryMock) GetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Ensure, that SoilMeasureRepositoryMock does implement SoilMeasureRepository.
// If this is not the case, regenerate this file with moq.
var _ SoilMeasureRepository = &SoilMeasureRepositoryMock{}

// SoilMeasureRepositoryMock is a mock implementation of SoilMeasureRepository.
//
//	func TestSomethingThatUsesSoilMeasureRepository(t *testing.T) {
//
//		// make and configure a mocked SoilMeasureRepository
//		mockedSoilMeasureRepository := &SoilMeasureRepositoryMock{
//			GetFunc: func(ctx context.Context) ([]SoilMeasure, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedSoilMeasureRepository in code that requires SoilMeasureRepository
//		// and then make assertions.
//
//	}
type SoilMeasureRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context) ([]SoilMeasure, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *SoilMeasureRepositoryMock) Get(ctx context.Context) ([]SoilMeasure, error) {
	if mock.GetFunc == nil {
		panic("SoilMeasureRepositoryMock.GetFunc: method is nil but SoilMeasureRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSoilMeasureRepository.GetCalls())
func (mock *SoilMeasureRepositoryMock) GetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Ensure, that ExecutionRepositoryMock does implement ExecutionRepository.
// If this is not the case, regenerate this file with moq.
var _ ExecutionRepository = &ExecutionRepositoryMock{}

// ExecutionRepositoryMock is a mock implementation of ExecutionRepository.
//
//	func TestSomethingThatUsesExecutionRepository(t *testing.T) {
//
//		// make and configure a mocked ExecutionRepository
//		mockedExecutionRepository := &ExecutionRepositoryMock{
//			GetLastExecutionFunc: func(ctx context.Context) (Executions, error) {
//				panic("mock out the GetLastExecution method")
//			},
//		}
//
//		// use mockedExecutionRepository in code that requires ExecutionRepository
//		// and then make assertions.
//
//	}
type ExecutionRepositoryMock struct {
	// GetLastExecutionFunc mocks the GetLastExecution method.
	GetLastExecutionFunc func(ctx context.Context) (Executions, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetLastExecution holds details about calls to the GetLastExecution method.
		GetLastExecution []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetLastExecution sync.RWMutex
}

// GetLastExecution calls GetLastExecutionFunc.
func (mock *ExecutionRepositoryMock) GetLastExecution(ctx context.Context) (Executions, error) {
	if mock.GetLastExecutionFunc == nil {
		panic("ExecutionRepositoryMock.GetLastExecutionFunc: method is nil but ExecutionRepository.GetLastExecution was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetLastExecution.Lock()
	mock.calls.GetLastExecution = append(mock.calls.GetLastExecution, callInfo)
	mock.lockGetLastExecution.Unlock()
	return mock.GetLastExecutionFunc(ctx)
}

// GetLastExecutionCalls gets all the calls that were made to GetLastExecution.
// Check the length with:
//
//	len(mockedExecutionRepository.GetLastExecutionCalls())
func (mock *ExecutionRepositoryMock) GetLastExecutionCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetLastExecution.RLock()
	calls = mock.calls.GetLastExecution
	mock.lockGetLastExecution.RUnlock()
	return calls
}

// Ensure, that HumidityReferenceRepositoryMock does implement HumidityReferenceRepository.
// If this is not the case, regenerate this file with moq.
var _ HumidityReferenceRepository = &HumidityReferenceRepositoryMock{}

// HumidityReferenceRepositoryMock is a mock implementation of HumidityReferenceRepository.
//
//	func TestSomethingThatUsesHumidityReferenceRepository(t *testing.T) {
//
//		// make and configure a mocked HumidityReferenceRepository
//		mockedHumidityReferenceRepository := &HumidityReferenceRepositoryMock{
//			GetByZoneFunc: func(ctx context.Context, zone string) (*HumidityReference, error) {
//				panic("mock out the GetByZone method")
//			},
//		}
//
//		// use mockedHumidityReferenceRepository in code that requires HumidityReferenceRepository
//		// and then make assertions.
//
//	}
type HumidityReferenceRepositoryMock struct {
	// GetByZoneFunc mocks the GetByZone method.
	GetByZoneFunc func(ctx context.Context, zone string) (*HumidityReference, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByZone holds details about calls to the GetByZone method.
		GetByZone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Zone is the zone argument value.
			Zone string
		}
	}
	lockGetByZone sync.RWMutex
}

// GetByZone calls GetByZoneFunc.
func (mock *HumidityReferenceRepositoryMock) GetByZone(ctx context.Context, zone string) (*HumidityReference, error) {
	if mock.GetByZoneFunc == nil {
		panic("HumidityReferenceRepositoryMock.GetByZoneFunc: method is nil but HumidityReferenceRepository.GetByZone was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Zone string
	}{
		Ctx:  ctx,
		Zone: zone,
	}
	mock.lockGetByZone.Lock()
	mock.calls.GetByZone = append(mock.calls.GetByZone, callInfo)
	mock.lockGetByZone.Unlock()
	return mock.GetByZoneFunc(ctx, zone)
}

// GetByZoneCalls gets all the calls that were made to GetByZone.
// Check the length with:
//
//	len(mockedHumidityReferenceRepository.GetByZoneCalls())
func (mock *HumidityReferenceRepositoryMock) GetByZoneCalls() []struct {
	Ctx  context.Context
	Zone string
} {
	var calls []struct {
		Ctx  context.Context
		Zone string
	}
	mock.lockGetByZone.RLock()
	calls = mock.calls.GetByZone
	mock.lockGetByZone.RUnlock()
	return calls
}

// Ensure, that StatusRepositoryMock does implement StatusRepository.
// If this is not the case, regenerate this file with moq.
var _ StatusRepository = &StatusRepositoryMock{}

// StatusRepositoryMock is a mock implementation of StatusRepository.
//
//	func TestSomethingThatUsesStatusRepository(t *testing.T) {
//
//		// make and configure a mocked StatusRepository
//		mockedStatusRepository := &StatusRepositoryMock{
//			GetStatusFunc: func(ctx context.Context) (*Status, error) {
//				panic("mock out the GetStatus method")
//			},
//		}
//
//		// use mockedStatusRepository in code that requires StatusRepository
//		// and then make assertions.
//
//	}
type StatusRepositoryMock struct {
	// GetStatusFunc mocks the GetStatus method.
	GetStatusFunc func(ctx context.Context) (*Status, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetStatus holds details about calls to the GetStatus method.
		GetStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetStatus sync.RWMutex
}

// GetStatus calls GetStatusFunc.
func (mock *StatusRepositoryMock) GetStatus(ctx context.Context) (*Status, error) {
	if mock.GetStatusFunc == nil {
		panic("StatusRepositoryMock.GetStatusFunc: method is nil but StatusRepository.GetStatus was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetStatus.Lock()
	mock.calls.GetStatus = append(mock.calls.GetStatus, callInfo)
	mock.lockGetStatus.Unlock()
	return mock.GetStatusFunc(ctx)
}

// GetStatusCalls gets all the calls that were made to GetStatus.
// Check the length with:
//
//	len(mockedStatusRepository.GetStatusCalls())
func (mock *StatusRepositoryMock) GetStatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetStatus.RLock()
	calls = mock.calls.GetStatus
	mock.lockGetStatus.RUnlock()
	return calls
}
